PE-8498 Manage System Interfaces
Roblox/terraform-provider-maas pull request #11
Opened 2020-02-18 04:29 UTC by onwsk8r

Use the `maas_interface_physical` resource:

```hcl
resource "maas_interface_physical" "myserver_eth0" {
  system_id   = maas_instance.myserver.system_id
  name        = "eth0"
  mac_address = "01:23:45:67:89:0A"
  tags        = ["foo", "bar"]
  vlan        = "my_vlan"
  mtu         = 1500
  accept_ra   = true
  autoconf    = true
}
```

2020-02-20 18:13 UTC, liskl reviewed
the code itself looks good, and tests pass as well as compiles, i'm not 100% following all the code flow, but my sampling all looks good, he provider doesn't have much in the way of tests yet because we don't have infra allocated to test the provider
```
PASS
ok  	github.com/roblox/terraform-provider-maas	2.113s
?   	github.com/roblox/terraform-provider-maas/internal/bridge	[no test files]
PASS
ok  	github.com/roblox/terraform-provider-maas/internal/provider	1.335s
PASS
ok  	github.com/roblox/terraform-provider-maas/internal/tfschema	1.334s
?   	github.com/roblox/terraform-provider-maas/pkg/api	[no test files]
?   	github.com/roblox/terraform-provider-maas/pkg/api/params	[no test files]
PASS
ok  	github.com/roblox/terraform-provider-maas/pkg/gmaw	1.336s
PASS
ok  	github.com/roblox/terraform-provider-maas/pkg/maas	1.230s
PASS
ok  	github.com/roblox/terraform-provider-maas/pkg/maas/entity	1.247s
PASS
ok  	github.com/roblox/terraform-provider-maas/pkg/maas/entity/subnet	1.240s
?   	github.com/roblox/terraform-provider-maas/test/helper	[no test files]
```

2020-02-21 00:39 UTC, robloxrob requested changes
Docs as needed. Amazing work!!!!!!!!!!!!!! 🥇

2020-02-21 00:39 UTC, robloxrob commented on README.md
> +resource "maas_interface_physical" "myserver_eth0" {
Thank you for adding this to the readme

2020-02-21 00:39 UTC, robloxrob commented on pkg/maas/entity/subnet/statistics.go
> +type Statistics struct {
docs as needed

2020-02-27 16:29 UTC, merged